### ISSUE TITLE
Issue to track current work progress

### ISSUE THREAD

**Issue by sn99** [tanveerraza789/watchmyfiles#1]
- [ ] Add license AGPL
- [ ] Setup CI/CD using github actions
- [ ] Convert it into a library and publish to `crates.io` 
  - [ ]  Add `dilawar` and `sn99` to owners list 
 - [ ] Improve documentation
- [ ] Move repo to [SubconsciousCompute](https://github.com/SubconsciousCompute)

 You can use [this](https://github.com/SubconsciousCompute/query-wmi) for reference. We will later also work on adding permission manager of sorts.

**Comment by tanveerraza789** [comment]
@sn99 I'm deleting this repo and making a new one.
